# This rule is not used by the project thecluster-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over pia.thecluster.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: thecluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: pia-wireguardconfig-admin-role
rules:
- apiGroups:
  - pia.thecluster.io
  resources:
  - wireguardconfigs
  verbs:
  - '*'
- apiGroups:
  - pia.thecluster.io
  resources:
  - wireguardconfigs/status
  verbs:
  - get
