kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: thecluster-operator
networking:
  # Don't use host search paths. This helps when the host machine has a
  # weird DNS config such as my home rig because networking is confusing
  dnsSearch: []
