apiVersion: actions.thecluster.io/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: thecluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: dotfiles
spec:
  url: https://github.com/UnstoppableMango/dotfiles
