name: CI

on:
  pull_request:
    branches: [main]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
